name: Run tests on CI
on:
  push:
    branches: main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.10'
        bundler-cache: true
    - name: Run tests
      run: rake features:ci_tests CHROMEDRIVER=${{ github.workspace }}/features/support/driver/chromedriver_linux/chromedriver