name: Run tests on CI
on:
  push:
    branches: main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: bundle exec cucumber --format summary --format html --out report.html